USE [master]
GO

/****** Objekt:  Database [Zahnarztpraxis]    Skriptdatum: 27.08.2026 14:57:55 ******/
CREATE DATABASE [Zahnarztpraxis]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Zahnarztpraxis', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL17.MSSQLSERVER\MSSQL\DATA\Zahnarztpraxis.mdf' , SIZE = 73728KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Zahnarztpraxis_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL17.MSSQLSERVER\MSSQL\DATA\Zahnarztpraxis_log.ldf' , SIZE = 25984KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Zahnarztpraxis].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Zahnarztpraxis] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Zahnarztpraxis] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Zahnarztpraxis] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Zahnarztpraxis] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Zahnarztpraxis] SET ARITHABORT OFF 
GO

ALTER DATABASE [Zahnarztpraxis] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Zahnarztpraxis] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Zahnarztpraxis] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Zahnarztpraxis] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Zahnarztpraxis] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Zahnarztpraxis] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Zahnarztpraxis] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Zahnarztpraxis] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Zahnarztpraxis] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Zahnarztpraxis] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Zahnarztpraxis] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Zahnarztpraxis] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Zahnarztpraxis] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Zahnarztpraxis] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Zahnarztpraxis] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Zahnarztpraxis] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Zahnarztpraxis] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Zahnarztpraxis] SET RECOVERY FULL 
GO

ALTER DATABASE [Zahnarztpraxis] SET  MULTI_USER 
GO

ALTER DATABASE [Zahnarztpraxis] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Zahnarztpraxis] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Zahnarztpraxis] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Zahnarztpraxis] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Zahnarztpraxis] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Zahnarztpraxis] SET OPTIMIZED_LOCKING = OFF 
GO

ALTER DATABASE [Zahnarztpraxis] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Zahnarztpraxis] SET QUERY_STORE = ON
GO

ALTER DATABASE [Zahnarztpraxis] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [Zahnarztpraxis] SET  READ_WRITE 
GO

